num_faces: 1
show_landmarks: False
show_mask: True
mask_type: 'frontman'

alignment_params:
  ma_scale_length: 10
  ma_position_length: 3
  ma_rotation_length: 5


#parameters for different types of masks

frontman: 1

half_ram: 1
