num_faces: 1
show_landmarks: False
show_mask: True
mesh_params:
  mesh_color: [0.2, 0.2, 0.2]
  render_color: [0.2, 0.2, 0.2, 1] #RGBA
  ma_scale_length: 10
  ma_position_length: 3
  ma_rotation_length: 5