num_faces: 1
show_landmarks: False
show_mask: True
mask_type: "frontman"

alignment_params:
  ma_scale_length: 10
  ma_position_length: 3
  ma_rotation_length: 5


#parameters for different types of masks

frontman:
  model_path: "./data/3d_models/frontman/Mask.stl"
  texture_path: None
  mesh_color: (0.2, 0.2, 0.2)
  eye_coordinates: [[-0.01, 0.125, 0.5], [-0.01, 0.125, -0.5]]
  initial_rotation:
    x: 0
    y: 90
    z: 0
  background_color: (1, 1, 1)
  color_threshold: 150 #color threshold for separation of the mask from backgroud
half_ram: 1
